options:
  layer_type: 'base'
  name: 'rocky-base'
  publish_tags: '8.10'
  pkg_manager: 'dnf'
  parent: 'scratch'
  publish_registry: 'registry.dist.si.usrc:5000/stratus'
  registry_opts_push:
    - '--tls-verify=false'

repos:
  - alias: 'Rock_BaseOS'
    url: 'https://dl.rockylinux.org/pub/rocky/8/BaseOS/x86_64/os'
    gpg: 'https://dl.rockylinux.org/pub/rocky/RPM-GPG-KEY-Rocky-8'
  - alias: 'Rock_AppStream'
    url: 'https://dl.rockylinux.org/pub/rocky/8/AppStream/x86_64/os'
    gpg: 'https://dl.rockylinux.org/pub/rocky/RPM-GPG-KEY-Rocky-8'
  - alias: 'Rock_PowerTools'
    url: 'https://dl.rockylinux.org/pub/rocky/8/PowerTools/x86_64/os'
    gpg: 'https://dl.rockylinux.org/pub/rocky/RPM-GPG-KEY-Rocky-8'

package_groups:
  - 'Minimal Install'
  - 'Development Tools'

packages:
  - kernel
  - wget
  - dracut-live
  - epel-release
  - elrepo-release

cmds:
  - cmd: '/usr/bin/crb enable'
